import { defineConfig } from 'vitepress';

// Site de documentation LibXN / QPath — bilingue (fr par défaut, en sous /en/).
export default defineConfig({
  title: 'LibXN · QPath',
  // lastUpdated désactivé : il lance `git log` par page → "spawn git ENOENT" si git n'est pas dans
  // le PATH du serveur dev (et nécessite des fichiers commités). Réactivable une fois git dispo + repo commité.
  lastUpdated: false,
  cleanUrls: true,
  head: [
    ['link', { rel: 'icon', type: 'image/svg+xml', href: '/favicon.svg' }],
    ['meta', { name: 'theme-color', content: '#06b6d4' }],
  ],
  // README.md sert d'index GitHub ; le site a sa propre home (index.md). Les .ts d'exemples ne sont pas des pages.
  // ⚠️ Doc technique détaillée EXCLUE du site public (protection IP) : concepts (dont le mapping
  // bit→direction), spécification formelle QPath, et référence d'API. Les fichiers .md restent dans
  // le repo pour usage interne, mais ne sont PAS générés dans le site.
  srcExclude: [
    'README.md', 'en/README.md',
    '01-concepts/**', 'en/01-concepts/**',
    '02-spec/**', 'en/02-spec/**',
    '03-api/**', 'en/03-api/**',
  ],
  // Les liens vers les exemples .ts pointent vers des fichiers source du repo, pas des pages du site.
  ignoreDeadLinks: [/examples/, /\.ts$/],
  themeConfig: {
    logo: '/logo.svg',
    search: { provider: 'local' },
    socialLinks: [
      { icon: 'linkedin', link: 'https://www.linkedin.com/in/bigvai-asgard-marcella-62b892221/' },
    ],
  },
  locales: {
    // ── Français (locale par défaut, à la racine) ──
    root: {
      label: 'Français',
      lang: 'fr-FR',
      description: 'QPath — mémoire symbolique adressable par contenu, en un seul graphe.',
      themeConfig: {
        nav: [
          { text: 'Aperçu', link: '/00-overview' },
          { text: 'Pourquoi QPath', link: '/why-qpath' },
          { text: 'Connaissance discrète', link: '/discrete-knowledge' },
          { text: 'Compréhension', link: '/comprehension' },
          { text: 'Performance & garanties', link: '/performance' },
          { text: 'Raisonnement', items: [
            { text: 'Types de raisonnement', link: '/reasoning-types' },
            { text: 'Flash reasoning', link: '/flash-reasoning' },
            { text: 'PingPong reasoning', link: '/pingpong-reasoning' },
            { text: 'Plot reasoning', link: '/plot-reasoning' },
            { text: 'Big Bang reasoning', link: '/big-bang' },
            { text: 'Proactive deduction', link: '/insight-reasoning' },
            { text: 'Déduction générative', link: '/generative-deduction' },
            { text: 'Factflow', link: '/dynamic-behavior' },
            { text: 'UI pilotée par faits', link: '/fact-driven-ui' },
            { text: "Couche d'accès", link: '/access-layer' },
            { text: 'Grand livre', link: '/transaction-ledger' },
          ] },
          { text: 'Mémoire & outils', items: [
            { text: 'Composants', link: '/components' },
            { text: 'Types de faits', link: '/fact-types' },
            { text: 'Media', link: '/media' },
            { text: 'Sous-couches', link: '/layers' },
            { text: 'Provenance', link: '/fact-provenance' },
            { text: 'Hygiène des faits (GC & Ajuster)', link: '/fact-maintenance' },
            { text: 'Persistance', link: '/persistence' },
            { text: 'Outils', link: '/tools' },
            { text: "Cas d'usage", link: '/use-cases' },
          ] },
          { text: 'Démarrer', items: [
            { text: 'Premier projet (Express)', link: '/first-project' },
            { text: 'Exemples', link: '/examples' },
            { text: 'Guide de démarrage', link: '/04-guides/getting-started' },
            { text: 'Architecture', link: '/04-guides/architecture' },
          ] },
          { text: 'Auteur', link: '/author' },
        ],
        sidebar: [
          {
            text: 'Documentation',
            items: [
              { text: 'Aperçu', link: '/00-overview' },
              { text: 'Pourquoi QPath', link: '/why-qpath' },
              { text: 'Connaissance discrète', link: '/discrete-knowledge' },
              { text: 'Compréhension', link: '/comprehension' },
              { text: 'Performance & garanties', link: '/performance' },
              { text: 'Composants clés', link: '/components' },
              { text: 'Types de faits', link: '/fact-types' },
              { text: "Cas d'usage", link: '/use-cases' },
              { text: 'Exemples', link: '/examples' },
              { text: 'Types de raisonnement', link: '/reasoning-types' },
              { text: 'Flash reasoning · web · LLM', link: '/flash-reasoning' },
              { text: 'PingPong reasoning', link: '/pingpong-reasoning' },
              { text: 'Plot reasoning', link: '/plot-reasoning' },
              { text: 'Big Bang reasoning', link: '/big-bang' },
              { text: 'Proactive deduction', link: '/insight-reasoning' },
              { text: 'Déduction générative', link: '/generative-deduction' },
              { text: 'Factflow', link: '/dynamic-behavior' },
              { text: 'UI pilotée par faits', link: '/fact-driven-ui' },
              { text: 'Access layer', link: '/access-layer' },
              { text: 'Transaction ledger', link: '/transaction-ledger' },
              { text: 'Media', link: '/media' },
              { text: 'Sous-couches (mémoire en couches)', link: '/layers' },
              { text: 'Outils (Tools)', link: '/tools' },
              { text: 'Provenance & revérification', link: '/fact-provenance' },
              { text: 'Persistance', link: '/persistence' },
              { text: 'Démarrer', link: '/04-guides/getting-started' },
              { text: 'Architecture', link: '/04-guides/architecture' },
              { text: 'Premier projet (Express)', link: '/first-project' },
              { text: 'Auteur', link: '/author' },
            ],
          },
        ],
        docFooter: { prev: 'Précédent', next: 'Suivant' },
        outline: { label: 'Sur cette page' },
      },
    },

    // ── English (sous /en/) ──
    en: {
      label: 'English',
      lang: 'en-US',
      link: '/en/',
      description: 'QPath — a content-addressable symbolic memory, in a single graph.',
      themeConfig: {
        nav: [
          { text: 'Overview', link: '/en/00-overview' },
          { text: 'Why QPath', link: '/en/why-qpath' },
          { text: 'Discrete knowledge', link: '/en/discrete-knowledge' },
          { text: 'Comprehension', link: '/en/comprehension' },
          { text: 'Performance & guarantees', link: '/en/performance' },
          { text: 'Reasoning', items: [
            { text: 'Reasoning types', link: '/en/reasoning-types' },
            { text: 'Flash reasoning', link: '/en/flash-reasoning' },
            { text: 'PingPong reasoning', link: '/en/pingpong-reasoning' },
            { text: 'Plot reasoning', link: '/en/plot-reasoning' },
            { text: 'Big Bang reasoning', link: '/en/big-bang' },
            { text: 'Proactive deduction', link: '/en/insight-reasoning' },
            { text: 'Generative deduction', link: '/en/generative-deduction' },
            { text: 'Factflow', link: '/en/dynamic-behavior' },
            { text: 'Fact-driven UI', link: '/en/fact-driven-ui' },
            { text: 'Access layer', link: '/en/access-layer' },
              { text: 'Transaction ledger', link: '/en/transaction-ledger' },
          ] },
          { text: 'Memory & tools', items: [
            { text: 'Components', link: '/en/components' },
            { text: 'Fact types', link: '/en/fact-types' },
            { text: 'Media', link: '/en/media' },
            { text: 'Layers', link: '/en/layers' },
            { text: 'Provenance', link: '/en/fact-provenance' },
            { text: 'Persistence', link: '/en/persistence' },
            { text: 'Tools', link: '/en/tools' },
            { text: 'Use cases', link: '/en/use-cases' },
          ] },
          { text: 'Get started', items: [
            { text: 'First project (Express)', link: '/en/first-project' },
            { text: 'Examples', link: '/en/examples' },
            { text: 'Getting started', link: '/en/04-guides/getting-started' },
            { text: 'Architecture', link: '/en/04-guides/architecture' },
          ] },
          { text: 'Author', link: '/en/author' },
        ],
        sidebar: [
          {
            text: 'Documentation',
            items: [
              { text: 'Overview', link: '/en/00-overview' },
              { text: 'Why QPath', link: '/en/why-qpath' },
              { text: 'Discrete knowledge', link: '/en/discrete-knowledge' },
              { text: 'Comprehension', link: '/en/comprehension' },
              { text: 'Performance & guarantees', link: '/en/performance' },
              { text: 'Key components', link: '/en/components' },
              { text: 'Fact types', link: '/en/fact-types' },
              { text: 'Use cases', link: '/en/use-cases' },
              { text: 'Examples', link: '/en/examples' },
              { text: 'Reasoning types', link: '/en/reasoning-types' },
              { text: 'Flash reasoning · web · LLM', link: '/en/flash-reasoning' },
              { text: 'PingPong reasoning', link: '/en/pingpong-reasoning' },
              { text: 'Plot reasoning', link: '/en/plot-reasoning' },
              { text: 'Big Bang reasoning', link: '/en/big-bang' },
              { text: 'Proactive deduction', link: '/en/insight-reasoning' },
              { text: 'Generative deduction', link: '/en/generative-deduction' },
              { text: 'Factflow', link: '/en/dynamic-behavior' },
              { text: 'Fact-driven UI', link: '/en/fact-driven-ui' },
              { text: 'Access layer', link: '/en/access-layer' },
              { text: 'Transaction ledger', link: '/en/transaction-ledger' },
              { text: 'Media', link: '/en/media' },
              { text: 'Layers (layered memory)', link: '/en/layers' },
              { text: 'Tools', link: '/en/tools' },
              { text: 'Provenance & re-verification', link: '/en/fact-provenance' },
              { text: 'Fact hygiene (GC & adjuster)', link: '/en/fact-maintenance' },
              { text: 'Persistence', link: '/en/persistence' },
              { text: 'Getting started', link: '/en/04-guides/getting-started' },
              { text: 'Architecture', link: '/en/04-guides/architecture' },
              { text: 'First project (Express)', link: '/en/first-project' },
              { text: 'Author', link: '/en/author' },
            ],
          },
        ],
      },
    },
  },
});
